### ISSUE TITLE
Moving to lebab.io

### ISSUE THREAD

**Issue by mohebifar** [uniibu/lebab-ce#2]
Thanks for the great work. 

I would like to know if you are interested in moving this repo to the Lebab organization and CNAMEing lebab.io to it.

**Comment by uniibu** [comment]
Hi, sure i don't mind transferring this repo to Lebab org. 

Do you simply want to link to it like, https://lebab.io/lebab-ce? If so, i don't think i need to cname it once the repo is already on Lebab's org. You just have to publish it normally to github pages and it should automatically direct to it if you visit https://lebab.io/lebab-ce.

Or do you want to cname a subdomain to it? If so, then sure i can cname a subdomain of lebab to it.
Or do you mean CNAMEing the bare lebab.io domain to it? If so, i'm strongly against this idea since you will lose the original lebab.io page, and this repo is only a editor with no front page, introduction etc. Besides, i can't cname lebab.io domain since it is already attached to the orgs "lebab.io" repo. 

So my best suggestion is i can transfer this repo to Lebab's org and you can publish it normally to github pages. Then simply edit your lebab.io repo to link it as lebab.io/lebab-ce (lebab.io/reponame). But if my assumptions are wrong, please do tell me and let me know how to go about it. 

Cheers!

**Comment by mohebifar** [comment]
Actually, I was thinking about having the editor at the root of the site with no extra stuff. I believe that'd be enough and the editor explains Lebab pretty well. We probably don't need any extra pages. What do you think?

**Comment by mohebifar** [comment]
I noticed you have redirected it to your own website and it has stopped working. Can you please bring it back up?

**Comment by uniibu** [comment]
Hi, sorry for late response, im a bit busy on work lately. Anyway, im not
sure if its because of the reditect. It should basically work whichever
domain it is in. Anyhow, i will check it soon as i get on my pc. Cheers

**Comment by uniibu** [comment]
Hi, been awhile, sorry for that, too busy in other projects. Anyhow, i'd be willing to move this repo to lebab organization repo and cnaming it to lebab.io. Let me know if u still want to do this.  Cheers!
