### ISSUE TITLE
window.lebab is undefined in local builds

### ISSUE THREAD

**Issue by XhmikosR** [uniibu/lebab-ce#22]
I keep getting this error locally whne I run `npm run dev`.

If I remove [this script](https://github.com/uniibu/lebab-ce/blob/master/components/AppThirdSection.vue#L24) then it works sort of.

**Comment by uniibu** [comment]
This is pretty much because the process of taking the latest browserified version of `lebab` happens during build using a custom build script at https://github.com/uniibu/lebab-ce/blob/master/build.js and this script isnt ran by normal `nuxt`, it is why `window.lebab` is undefined. 

The reason why i did this aside from having not to worry about new releases of `lebab`, is because `lebab` it self does not have its own browser build, So one has to build it their own, or include the lebab module on their own respective frameworks. 

Thank you btw for the PRs 👍

**Comment by XhmikosR** [comment]
So how is one supposed to develop locally without this error?

**Comment by uniibu** [comment]
@XhmikosR This should be fixed now with `1.4.1` build.  I started migrating this repo to nuxt around May 2018 and I've barely updated most of the modules as i was very busy with other projects. 

The latest nuxt now allows async function calls inside `nuxt.config.js` so i removed the `build.js` and integrated it on the `nuxt.config.js` it self. Because of that change, it no longer needs to call a custom build script, thus allowing you to run `npm run dev` successfully.

**Comment by XhmikosR** [comment]
Perfect, works fine now, thanks!
