### ISSUE TITLE
Project dropped?

### ISSUE THREAD

**Issue by liyasthomas** [uniibu/lebab-ce#244]
This project is totally cool but seems like the development is somehow delayed or dropped.

I can see PRs as old as 6 months are not even merged.
What is the future of this project?

**Comment by uniibu** [comment]
Thanks for the interest in the project, however, this repo is merely a community maintained `Frontend` site of Lebab. The repo for the main Lebab is https://github.com/lebab/lebab

On the side note, afaik, the original Developer for Lebab has already abandoned the project and is now only maintained by another person. It is indeed a good project, but it now lacks contributors. I only maintain this repository because I still believe in the project. Feel free to visit the [Lebab ](https://github.com/lebab/lebab)repo.
